/*
 * This source file was generated by the Gradle 'init' task
 */
package ferreiras;

public class LeetCode {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LeetCode().getGreeting());
    }
}
